language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t valeriotrenta/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true valeriotrenta/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-784084495175"
  bucket_path: "docker-recat"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key:
    secure: "$AWS_SECRET_KEY"